apiVersion: v2
name: openqhse
description: OpenQHSE — Enterprise QHSE Management Platform
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: OpenQHSE Team
    url: https://github.com/openqhse
